advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    path("", views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path("basic_app/", include('basic_app.urls', namespace = "basic_app"))
]

advcbv/basic_app/urls.py
from django.conf.urls import url, include
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name = "list"),
    url(r'^create/$', views.SchoolCreateView.as_view(), name = "create"),
    # OVer here you might get an error of <Field 'id' expected a number but got 'create'>. So all you need to do is to just change the location of url line.
    # bring the line upword and try again and see it worked.
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name = "detail"),
    # OVer here we r saying grab the basic_app extension of the domain name/ and whatever number u detect over here is the primary key, grab it and take the user
    # to that specific primary key school detail. 
    # this regular expression is just being used to grab the primary key. 
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name = "update"),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name = "delete"),
]
 

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class School(models.Model):
    name = models.CharField(max_length = 256)
    principal = models.CharField(max_length = 256)
    location = models.CharField(max_length = 256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # once u create something new from database u create this view where ur django will redirect u. so django will redirect u on detail page. 
        return reverse("basic_app:detail", kwargs = {'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length = 256)
    age = models.PositiveIntegerField()  # this field will only take positive values.
    school = models.ForeignKey(School, related_name = 'students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    
# Now we will be registering these 2 dbs in admin.py file

advcbv/basic_app/views.py
from django.shortcuts import render
# from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import View, CreateView, UpdateView, DeleteView
from . import models  # . mean look in the current directory. 
from django.urls import reverse_lazy 

# Create your views here.
# Now we will explore template based Views Here.

class IndexView(TemplateView):
    template_name = "index.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)  # Just copy and paste this line. 
    #     # this is how u can use context in class based views. Context is basically template injection in index.html file.  
    #     context["injectme"] = "Basic Injection!"
    #     return context


#####################

# From Here we will talk about list view and Detail view. So far we have seen views and TemplateView.  
# For this first of all we need to create models. lets jump to model.py file

# I m gonna create a list view which is connected to a model. and it will fetch data from the model. 
class SchoolListView(ListView):
    # model = models.School
    # that's all u need  to do and u will be provided with a list of records stored in the school model(db)
    # it returns a list with the name school_list i.e. <MODEL_NAME>_list.
    # apart of this u can define your own context name i.e. 

    context_object_name = 'schools'
    model = models.School

# Now let's see what a detail view looks like. 
# Let's do the same thing for this class 
# Detail View
class SchoolDetailView(DetailView):
    # Note: DetialView class returns only model name lowercased.
    context_object_name = "school_detail"
    model = models.School
    # so here it will return school just.
    template_name = 'basic_app/school_detail.html'

# Create View
class SchoolCreateView(CreateView):
    # fields -> overhere we will define the fields that we will allow user to create.i.e. the fields that are defined in the database we need to create here as well.
    fields = ('name', 'principal', 'location')
    model = models.School

# Update View
class SchoolUpdateView(UpdateView):
    # again we will specify which fields you want to update. so below I m just changing school name and principal of school but not location.
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    # This is going to be slghtly different than the other views we created so far. 
    model = models.School
    success_url = reverse_lazy("basic_app:list") # list is the name of my view.

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container"> 
            <ul class="navbar-nav mr-auto">
                <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
                <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
              
            </ul>
        </div>    
    </nav>

    <div class="container">

        
        {% block body_block %}
        {% endblock %}

    </div>

</body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<h1>Delete {{school.name}}</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>  <!-- why we r passing primary key here. blc in detail url if u go to urls.py u will see
    the detail view is expecting some sort of primary key. -->

</form>





{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<div class="jumbotron">

    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details: </h2>
    <p>Name: {{ school_detail.name }}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>
    <h3>Students: </h3>

    {% for student in school_detail.students.all %}  <!-- students is a related_name that we defined in the models.py file. so it will link the student with his specific school -->
        <p>{{student.name}} who is {{student.age}} years old.</p>

    {% endfor %}

</div>

<div class="container">
    <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>

</div>

{% endblock%}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1> 
    {% if not form.instance.pk %}  <!-- mean if the instance of the primary key exist or not. if it doesn't exist that's mean that it is new 
                                school so it will run create school. -->
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" name="" value="Submit">


</form>


{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

    <h1>Welcome to the list of all the schools!</h1>
    <ol>
        {% for school in schools %}  <!-- In this views.py we havent define any context dictionary with the name school_list. so where is this context dictionary
                                        coming from. ListView automatically creates context dictionary for u. so actually it calls the model name(lowercase it) and add _list to it. -->
            <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
            
        {% endfor %}

    </ol>

{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container"> 
            <ul class="navbar-nav mr-auto">
                <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
                <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                
                
            </ul>
        </div>    
    </nav>

    <div class="container">

        
        {% block body_block %}
        {% endblock %}

    </div>

</body>
</html>

advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1>

    </div>    


{% endblock %}